### ISSUE TITLE
Improve import for better performance

### ISSUE THREAD

**Issue by Pavel910** [jakubknejzlik/apollo-gateway-aws-lambda#1]
Hi, I just wanted to leave a suggestion regarding the way you import `aws-sdk`:
```js
import { Lambda } from "aws-sdk";
```
This imports the entire `aws-sdk` with all the service clients, which is far from optimal especially if you're using this in a Lambda environment. That's a lot of wasted memory and processing, and you only need Lambda.

```js
import Lambda from "aws-sdk/clients/lambda";
```
This will only import the Lambda client and not the entire SDK.

Cheers!

**Comment by jakubknejzlik** [comment]
Hi @Pavel910 , I didn't expect that somebody notices this package as it's highly experimental 😃 . Anyway thanks for the performance tip, the cold start is now ~200ms faster (1100ms -> 900ms with 2 services) and also ~10MB less heavier on ram usage (155MB -> 145MB) with the same config. 👍

**Comment by Pavel910** [comment]
@jakubknejzlik I also need it for an experiment, so I searched `npm` before implementing it myself, and stumbled across your package :) Going to tinker with it right now 🍻 🚀

**Comment by jakubknejzlik** [comment]
Also for the sake of experimentation, maybe this can come in handy https://github.com/graphql-services/graphql-gateway
